/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const DrugStatus = IDL.Variant({
  'banned' : IDL.Null,
  'approved' : IDL.Null,
});
export const DrugSource = IDL.Variant({
  'other' : IDL.Text,
  'cdsco' : IDL.Null,
  'mimsIndia' : IDL.Null,
  'applicationData' : IDL.Null,
});
export const Drug = IDL.Record({
  'status' : DrugStatus,
  'source' : DrugSource,
  'date' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'safetyInfo' : IDL.Text,
});
export const InteractionType = IDL.Variant({
  'pharmacokinetic' : IDL.Null,
  'both' : IDL.Null,
  'pharmacodynamic' : IDL.Null,
});
export const EvidenceLevel = IDL.Variant({
  'clinicalTrial' : IDL.Null,
  'others' : IDL.Null,
  'regulatoryAgency' : IDL.Null,
  'metaAnalysis' : IDL.Null,
  'caseReport' : IDL.Null,
  'expertOpinion' : IDL.Null,
});
export const Severity = IDL.Variant({
  'major' : IDL.Null,
  'minor' : IDL.Null,
  'contraindicated' : IDL.Null,
  'moderate' : IDL.Null,
});
export const DrugInteraction = IDL.Record({
  'interactionType' : InteractionType,
  'references' : IDL.Vec(IDL.Text),
  'evidenceLevel' : EvidenceLevel,
  'description' : IDL.Text,
  'severity' : Severity,
  'drug1' : IDL.Text,
  'drug2' : IDL.Text,
});
export const ResourceStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'redirected' : IDL.Null,
  'archived' : IDL.Null,
  'unavailable' : IDL.Null,
});
export const ExternalResource = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'status' : ResourceStatus,
  'synchronizationLogs' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'lastUpdated' : Time,
  'description' : IDL.Text,
  'contentSummary' : IDL.Opt(IDL.Text),
});
export const RestrictedDrug = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'safetyInfo' : IDL.Text,
});
export const RestrictedDrugCategory = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'drugs' : IDL.Vec(RestrictedDrug),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BulkDrugStoreUpdateResult = IDL.Record({
  'added' : IDL.Nat,
  'errors' : IDL.Vec(IDL.Text),
  'duplicates' : IDL.Nat,
  'totalAfterStore' : IDL.Nat,
  'skippedEmpty' : IDL.Nat,
});
export const FourDrugInteractionInput = IDL.Record({
  'drug1' : IDL.Text,
  'drug2' : IDL.Text,
  'drug3' : IDL.Text,
  'drug4' : IDL.Text,
});
export const DrugInteractionPair = IDL.Record({
  'drugA' : IDL.Text,
  'drugB' : IDL.Text,
});
export const DrugPairResult = IDL.Record({
  'interactionType' : IDL.Opt(InteractionType),
  'references' : IDL.Vec(IDL.Text),
  'evidenceLevel' : IDL.Opt(EvidenceLevel),
  'description' : IDL.Opt(IDL.Text),
  'severity' : IDL.Opt(Severity),
  'drugs' : DrugInteractionPair,
});
export const FourDrugInteractionOutput = IDL.Record({
  'pairResults' : IDL.Vec(DrugPairResult),
  'overallSeverity' : IDL.Opt(IDL.Text),
});
export const AdverseDrugReaction = IDL.Record({
  'onsetDate' : IDL.Opt(Time),
  'adrId' : IDL.Text,
  'patientId' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'suspectedDrug' : IDL.Text,
  'severity' : IDL.Text,
});
export const Patient = IDL.Record({
  'age' : IDL.Nat,
  'bmi' : IDL.Float64,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'patientId' : IDL.Text,
  'name' : IDL.Text,
  'nationality' : IDL.Text,
  'bloodGroup' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'gender' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const NarrationStatus = IDL.Variant({
  'finalized' : IDL.Null,
  'reviewed' : IDL.Null,
  'draft' : IDL.Null,
});
export const CaseNarration = IDL.Record({
  'status' : NarrationStatus,
  'content' : IDL.Text,
  'generatedSummary' : IDL.Opt(IDL.Text),
  'patientId' : IDL.Text,
  'lastModified' : Time,
  'version' : IDL.Nat,
  'narrationId' : IDL.Text,
  'timestamp' : Time,
});
export const DrugCategoryType = IDL.Variant({
  'painkillers' : IDL.Null,
  'other' : IDL.Null,
  'fdcs' : IDL.Null,
  'antibiotics' : IDL.Null,
  'vitamins' : IDL.Null,
});
export const DrugWithCategory = IDL.Record({
  'categoryType' : DrugCategoryType,
  'drug' : Drug,
});
export const CategorizedDrugs = IDL.Record({
  'all' : IDL.Vec(DrugWithCategory),
  'painkillers' : IDL.Vec(DrugWithCategory),
  'fdcs' : IDL.Vec(DrugWithCategory),
  'others' : IDL.Vec(DrugWithCategory),
  'antibiotics' : IDL.Vec(DrugWithCategory),
  'vitamins' : IDL.Vec(DrugWithCategory),
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const SpecialPopulationsGuidance = IDL.Record({
  'lactation' : IDL.Opt(IDL.Text),
  'pediatrics' : IDL.Opt(IDL.Text),
  'pregnancy' : IDL.Opt(IDL.Text),
  'geriatrics' : IDL.Opt(IDL.Text),
});
export const ToxicityRiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'moderate' : IDL.Null,
  'unknown' : IDL.Null,
});
export const OverallRiskSummary = IDL.Record({
  'highestRiskLevel' : IDL.Opt(ToxicityRiskLevel),
  'topRecommendation' : IDL.Opt(IDL.Text),
  'overallSeverity' : IDL.Opt(Severity),
  'highestSeverityPair' : IDL.Opt(DrugInteractionPair),
});
export const ClinicallyOrientedInteraction = IDL.Record({
  'managementRecommendations' : IDL.Opt(IDL.Text),
  'interactionType' : IDL.Opt(InteractionType),
  'references' : IDL.Vec(IDL.Text),
  'evidenceLevel' : IDL.Opt(EvidenceLevel),
  'description' : IDL.Opt(IDL.Text),
  'severity' : IDL.Opt(Severity),
  'toxicityRisk' : IDL.Opt(ToxicityRiskLevel),
  'clinicalEffects' : IDL.Opt(IDL.Text),
  'drugs' : DrugInteractionPair,
});
export const DrugSafetyAdvisory = IDL.Record({
  'specialPopulations' : SpecialPopulationsGuidance,
  'overallRisk' : IDL.Opt(OverallRiskSummary),
  'pairwiseInteractions' : IDL.Vec(ClinicallyOrientedInteraction),
});
export const LabResults = IDL.Record({
  'patientId' : IDL.Text,
  'labResultsId' : IDL.Text,
  'timestamp' : Time,
  'bloodPressureDiastolic' : IDL.Opt(IDL.Nat),
  'creatinine' : IDL.Opt(IDL.Float64),
  'bloodPressureSystolic' : IDL.Opt(IDL.Nat),
  'uricAcid' : IDL.Opt(IDL.Float64),
});
export const DrugVerificationResult = IDL.Record({
  'verifiedBannedDrugs' : IDL.Vec(Drug),
  'verificationTimestamp' : Time,
  'allDrugs' : IDL.Vec(Drug),
  'verifiedApprovedDrugs' : IDL.Vec(Drug),
});
export const Medication = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'dosage' : IDL.Opt(IDL.Text),
  'patientId' : IDL.Text,
  'name' : IDL.Text,
  'medicationId' : IDL.Text,
  'timestamp' : Time,
  'frequency' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Opt(Time),
});
export const PrescriberPrefix = IDL.Variant({
  'doctor' : IDL.Null,
  'pharmacist' : IDL.Null,
  'practitionerNurse' : IDL.Null,
});
export const PrescriberDetails = IDL.Record({
  'fullName' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'specialization' : IDL.Text,
  'prefix' : PrescriberPrefix,
  'contactNumber' : IDL.Text,
});
export const OCRStatus = IDL.Variant({
  'pending' : IDL.Null,
  'processed' : IDL.Null,
  'failed' : IDL.Null,
});
export const PrescriptionImage = IDL.Record({
  'id' : IDL.Text,
  'patientId' : IDL.Text,
  'errorMessage' : IDL.Opt(IDL.Text),
  'ocrStatus' : OCRStatus,
  'extractedText' : IDL.Opt(IDL.Text),
  'processingTime' : IDL.Opt(Time),
  'imageUrl' : IDL.Text,
  'uploadTime' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addADR' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Time)],
      [
        IDL.Record({
          'status' : IDL.Text,
          'adrId' : IDL.Opt(IDL.Text),
          'error' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'addCaseNarration' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'status' : IDL.Text,
          'error' : IDL.Opt(IDL.Text),
          'narrationId' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addDrug' : IDL.Func([Drug], [], []),
  'addDrugInteraction' : IDL.Func([DrugInteraction], [], []),
  'addExternalResource' : IDL.Func([ExternalResource], [], []),
  'addLabResults' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [
        IDL.Record({
          'status' : IDL.Text,
          'labResultsId' : IDL.Opt(IDL.Text),
          'error' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'addMedication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        IDL.Opt(Time),
      ],
      [
        IDL.Record({
          'status' : IDL.Text,
          'error' : IDL.Opt(IDL.Text),
          'medicationId' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'addNewPatient' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [
        IDL.Record({
          'status' : IDL.Text,
          'patientId' : IDL.Opt(IDL.Text),
          'error' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'addPrescriptionImage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'status' : IDL.Text,
          'error' : IDL.Opt(IDL.Text),
          'imageId' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
  'addRestrictedDrugCategory' : IDL.Func([RestrictedDrugCategory], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdateDrugDatabaseStore' : IDL.Func(
      [IDL.Vec(Drug)],
      [BulkDrugStoreUpdateResult],
      [],
    ),
  'bulkUpdateDrugTableStore' : IDL.Func(
      [IDL.Vec(Drug)],
      [BulkDrugStoreUpdateResult],
      [],
    ),
  'checkDrugInteraction' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(DrugInteraction)],
      [],
    ),
  'checkFourDrugInteraction' : IDL.Func(
      [FourDrugInteractionInput],
      [FourDrugInteractionOutput],
      [],
    ),
  'deletePatient' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'status' : IDL.Text, 'error' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'getADRsByPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AdverseDrugReaction)],
      ['query'],
    ),
  'getAllDrugDatabaseStoreDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
  'getAllDrugTableStoreDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
  'getAllDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
  'getAllDrugsFromDatabase' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
  'getAllDrugsFromStore' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getApprovedDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
  'getAuthoritativeDrugDatabase' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
  'getAuthoritativeDrugDatabaseByStatus' : IDL.Func(
      [DrugStatus],
      [IDL.Vec(Drug)],
      ['query'],
    ),
  'getBannedDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseNarrationsByPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CaseNarration)],
      ['query'],
    ),
  'getCategorizedDrugs' : IDL.Func([], [CategorizedDrugs], ['query']),
  'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getDrugDatabaseStoreByStatus' : IDL.Func(
      [DrugStatus],
      [IDL.Vec(Drug)],
      ['query'],
    ),
  'getDrugSafetyAdvisory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [DrugSafetyAdvisory],
      ['query'],
    ),
  'getDrugTableLastRefreshTimestamp' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getDrugTableStoreByStatus' : IDL.Func(
      [DrugStatus],
      [IDL.Vec(Drug)],
      ['query'],
    ),
  'getDrugTableVerificationReport' : IDL.Func(
      [],
      [
        IDL.Record({
          'lastVerificationTimestamp' : IDL.Opt(Time),
          'bannedDrugs' : IDL.Nat,
          'lastVerifiedDrugCount' : IDL.Opt(IDL.Nat),
          'approvedDrugs' : IDL.Nat,
          'totalDrugs' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getExternalResources' : IDL.Func([], [IDL.Vec(ExternalResource)], ['query']),
  'getFilteredDrugs' : IDL.Func(
      [IDL.Opt(DrugStatus)],
      [IDL.Vec(Drug)],
      ['query'],
    ),
  'getLabResultsByPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LabResults)],
      ['query'],
    ),
  'getLastDrugVerification' : IDL.Func(
      [],
      [IDL.Opt(DrugVerificationResult)],
      ['query'],
    ),
  'getMedicationsByPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Medication)],
      ['query'],
    ),
  'getPrescriberDetailsByPatientId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PrescriberDetails)],
      ['query'],
    ),
  'getPrescriptionImagesByPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PrescriptionImage)],
      ['query'],
    ),
  'getRestrictedDrugCategories' : IDL.Func(
      [],
      [IDL.Vec(RestrictedDrugCategory)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'refreshAndVerifyDrugTable' : IDL.Func([], [DrugVerificationResult], []),
  'refreshAuthoritativeAggregateDatabase' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePrescriberDetailsForPatient' : IDL.Func(
      [IDL.Text, PrescriberDetails],
      [],
      [],
    ),
  'searchDrugs' : IDL.Func([IDL.Text], [IDL.Vec(Drug)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const DrugStatus = IDL.Variant({
    'banned' : IDL.Null,
    'approved' : IDL.Null,
  });
  const DrugSource = IDL.Variant({
    'other' : IDL.Text,
    'cdsco' : IDL.Null,
    'mimsIndia' : IDL.Null,
    'applicationData' : IDL.Null,
  });
  const Drug = IDL.Record({
    'status' : DrugStatus,
    'source' : DrugSource,
    'date' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'safetyInfo' : IDL.Text,
  });
  const InteractionType = IDL.Variant({
    'pharmacokinetic' : IDL.Null,
    'both' : IDL.Null,
    'pharmacodynamic' : IDL.Null,
  });
  const EvidenceLevel = IDL.Variant({
    'clinicalTrial' : IDL.Null,
    'others' : IDL.Null,
    'regulatoryAgency' : IDL.Null,
    'metaAnalysis' : IDL.Null,
    'caseReport' : IDL.Null,
    'expertOpinion' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'major' : IDL.Null,
    'minor' : IDL.Null,
    'contraindicated' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const DrugInteraction = IDL.Record({
    'interactionType' : InteractionType,
    'references' : IDL.Vec(IDL.Text),
    'evidenceLevel' : EvidenceLevel,
    'description' : IDL.Text,
    'severity' : Severity,
    'drug1' : IDL.Text,
    'drug2' : IDL.Text,
  });
  const ResourceStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'redirected' : IDL.Null,
    'archived' : IDL.Null,
    'unavailable' : IDL.Null,
  });
  const ExternalResource = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'status' : ResourceStatus,
    'synchronizationLogs' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'lastUpdated' : Time,
    'description' : IDL.Text,
    'contentSummary' : IDL.Opt(IDL.Text),
  });
  const RestrictedDrug = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'safetyInfo' : IDL.Text,
  });
  const RestrictedDrugCategory = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'drugs' : IDL.Vec(RestrictedDrug),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BulkDrugStoreUpdateResult = IDL.Record({
    'added' : IDL.Nat,
    'errors' : IDL.Vec(IDL.Text),
    'duplicates' : IDL.Nat,
    'totalAfterStore' : IDL.Nat,
    'skippedEmpty' : IDL.Nat,
  });
  const FourDrugInteractionInput = IDL.Record({
    'drug1' : IDL.Text,
    'drug2' : IDL.Text,
    'drug3' : IDL.Text,
    'drug4' : IDL.Text,
  });
  const DrugInteractionPair = IDL.Record({
    'drugA' : IDL.Text,
    'drugB' : IDL.Text,
  });
  const DrugPairResult = IDL.Record({
    'interactionType' : IDL.Opt(InteractionType),
    'references' : IDL.Vec(IDL.Text),
    'evidenceLevel' : IDL.Opt(EvidenceLevel),
    'description' : IDL.Opt(IDL.Text),
    'severity' : IDL.Opt(Severity),
    'drugs' : DrugInteractionPair,
  });
  const FourDrugInteractionOutput = IDL.Record({
    'pairResults' : IDL.Vec(DrugPairResult),
    'overallSeverity' : IDL.Opt(IDL.Text),
  });
  const AdverseDrugReaction = IDL.Record({
    'onsetDate' : IDL.Opt(Time),
    'adrId' : IDL.Text,
    'patientId' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'suspectedDrug' : IDL.Text,
    'severity' : IDL.Text,
  });
  const Patient = IDL.Record({
    'age' : IDL.Nat,
    'bmi' : IDL.Float64,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'patientId' : IDL.Text,
    'name' : IDL.Text,
    'nationality' : IDL.Text,
    'bloodGroup' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'gender' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const NarrationStatus = IDL.Variant({
    'finalized' : IDL.Null,
    'reviewed' : IDL.Null,
    'draft' : IDL.Null,
  });
  const CaseNarration = IDL.Record({
    'status' : NarrationStatus,
    'content' : IDL.Text,
    'generatedSummary' : IDL.Opt(IDL.Text),
    'patientId' : IDL.Text,
    'lastModified' : Time,
    'version' : IDL.Nat,
    'narrationId' : IDL.Text,
    'timestamp' : Time,
  });
  const DrugCategoryType = IDL.Variant({
    'painkillers' : IDL.Null,
    'other' : IDL.Null,
    'fdcs' : IDL.Null,
    'antibiotics' : IDL.Null,
    'vitamins' : IDL.Null,
  });
  const DrugWithCategory = IDL.Record({
    'categoryType' : DrugCategoryType,
    'drug' : Drug,
  });
  const CategorizedDrugs = IDL.Record({
    'all' : IDL.Vec(DrugWithCategory),
    'painkillers' : IDL.Vec(DrugWithCategory),
    'fdcs' : IDL.Vec(DrugWithCategory),
    'others' : IDL.Vec(DrugWithCategory),
    'antibiotics' : IDL.Vec(DrugWithCategory),
    'vitamins' : IDL.Vec(DrugWithCategory),
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const SpecialPopulationsGuidance = IDL.Record({
    'lactation' : IDL.Opt(IDL.Text),
    'pediatrics' : IDL.Opt(IDL.Text),
    'pregnancy' : IDL.Opt(IDL.Text),
    'geriatrics' : IDL.Opt(IDL.Text),
  });
  const ToxicityRiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'moderate' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const OverallRiskSummary = IDL.Record({
    'highestRiskLevel' : IDL.Opt(ToxicityRiskLevel),
    'topRecommendation' : IDL.Opt(IDL.Text),
    'overallSeverity' : IDL.Opt(Severity),
    'highestSeverityPair' : IDL.Opt(DrugInteractionPair),
  });
  const ClinicallyOrientedInteraction = IDL.Record({
    'managementRecommendations' : IDL.Opt(IDL.Text),
    'interactionType' : IDL.Opt(InteractionType),
    'references' : IDL.Vec(IDL.Text),
    'evidenceLevel' : IDL.Opt(EvidenceLevel),
    'description' : IDL.Opt(IDL.Text),
    'severity' : IDL.Opt(Severity),
    'toxicityRisk' : IDL.Opt(ToxicityRiskLevel),
    'clinicalEffects' : IDL.Opt(IDL.Text),
    'drugs' : DrugInteractionPair,
  });
  const DrugSafetyAdvisory = IDL.Record({
    'specialPopulations' : SpecialPopulationsGuidance,
    'overallRisk' : IDL.Opt(OverallRiskSummary),
    'pairwiseInteractions' : IDL.Vec(ClinicallyOrientedInteraction),
  });
  const LabResults = IDL.Record({
    'patientId' : IDL.Text,
    'labResultsId' : IDL.Text,
    'timestamp' : Time,
    'bloodPressureDiastolic' : IDL.Opt(IDL.Nat),
    'creatinine' : IDL.Opt(IDL.Float64),
    'bloodPressureSystolic' : IDL.Opt(IDL.Nat),
    'uricAcid' : IDL.Opt(IDL.Float64),
  });
  const DrugVerificationResult = IDL.Record({
    'verifiedBannedDrugs' : IDL.Vec(Drug),
    'verificationTimestamp' : Time,
    'allDrugs' : IDL.Vec(Drug),
    'verifiedApprovedDrugs' : IDL.Vec(Drug),
  });
  const Medication = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'dosage' : IDL.Opt(IDL.Text),
    'patientId' : IDL.Text,
    'name' : IDL.Text,
    'medicationId' : IDL.Text,
    'timestamp' : Time,
    'frequency' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Opt(Time),
  });
  const PrescriberPrefix = IDL.Variant({
    'doctor' : IDL.Null,
    'pharmacist' : IDL.Null,
    'practitionerNurse' : IDL.Null,
  });
  const PrescriberDetails = IDL.Record({
    'fullName' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'specialization' : IDL.Text,
    'prefix' : PrescriberPrefix,
    'contactNumber' : IDL.Text,
  });
  const OCRStatus = IDL.Variant({
    'pending' : IDL.Null,
    'processed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PrescriptionImage = IDL.Record({
    'id' : IDL.Text,
    'patientId' : IDL.Text,
    'errorMessage' : IDL.Opt(IDL.Text),
    'ocrStatus' : OCRStatus,
    'extractedText' : IDL.Opt(IDL.Text),
    'processingTime' : IDL.Opt(Time),
    'imageUrl' : IDL.Text,
    'uploadTime' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addADR' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Time)],
        [
          IDL.Record({
            'status' : IDL.Text,
            'adrId' : IDL.Opt(IDL.Text),
            'error' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'addCaseNarration' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'status' : IDL.Text,
            'error' : IDL.Opt(IDL.Text),
            'narrationId' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addDrug' : IDL.Func([Drug], [], []),
    'addDrugInteraction' : IDL.Func([DrugInteraction], [], []),
    'addExternalResource' : IDL.Func([ExternalResource], [], []),
    'addLabResults' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [
          IDL.Record({
            'status' : IDL.Text,
            'labResultsId' : IDL.Opt(IDL.Text),
            'error' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'addMedication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          IDL.Opt(Time),
        ],
        [
          IDL.Record({
            'status' : IDL.Text,
            'error' : IDL.Opt(IDL.Text),
            'medicationId' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'addNewPatient' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [
          IDL.Record({
            'status' : IDL.Text,
            'patientId' : IDL.Opt(IDL.Text),
            'error' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'addPrescriptionImage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'status' : IDL.Text,
            'error' : IDL.Opt(IDL.Text),
            'imageId' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'addRestrictedDrugCategory' : IDL.Func([RestrictedDrugCategory], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdateDrugDatabaseStore' : IDL.Func(
        [IDL.Vec(Drug)],
        [BulkDrugStoreUpdateResult],
        [],
      ),
    'bulkUpdateDrugTableStore' : IDL.Func(
        [IDL.Vec(Drug)],
        [BulkDrugStoreUpdateResult],
        [],
      ),
    'checkDrugInteraction' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(DrugInteraction)],
        [],
      ),
    'checkFourDrugInteraction' : IDL.Func(
        [FourDrugInteractionInput],
        [FourDrugInteractionOutput],
        [],
      ),
    'deletePatient' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'status' : IDL.Text, 'error' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'getADRsByPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdverseDrugReaction)],
        ['query'],
      ),
    'getAllDrugDatabaseStoreDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
    'getAllDrugTableStoreDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
    'getAllDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
    'getAllDrugsFromDatabase' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
    'getAllDrugsFromStore' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getApprovedDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
    'getAuthoritativeDrugDatabase' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
    'getAuthoritativeDrugDatabaseByStatus' : IDL.Func(
        [DrugStatus],
        [IDL.Vec(Drug)],
        ['query'],
      ),
    'getBannedDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseNarrationsByPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CaseNarration)],
        ['query'],
      ),
    'getCategorizedDrugs' : IDL.Func([], [CategorizedDrugs], ['query']),
    'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getDrugDatabaseStoreByStatus' : IDL.Func(
        [DrugStatus],
        [IDL.Vec(Drug)],
        ['query'],
      ),
    'getDrugSafetyAdvisory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [DrugSafetyAdvisory],
        ['query'],
      ),
    'getDrugTableLastRefreshTimestamp' : IDL.Func(
        [],
        [IDL.Opt(Time)],
        ['query'],
      ),
    'getDrugTableStoreByStatus' : IDL.Func(
        [DrugStatus],
        [IDL.Vec(Drug)],
        ['query'],
      ),
    'getDrugTableVerificationReport' : IDL.Func(
        [],
        [
          IDL.Record({
            'lastVerificationTimestamp' : IDL.Opt(Time),
            'bannedDrugs' : IDL.Nat,
            'lastVerifiedDrugCount' : IDL.Opt(IDL.Nat),
            'approvedDrugs' : IDL.Nat,
            'totalDrugs' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getExternalResources' : IDL.Func(
        [],
        [IDL.Vec(ExternalResource)],
        ['query'],
      ),
    'getFilteredDrugs' : IDL.Func(
        [IDL.Opt(DrugStatus)],
        [IDL.Vec(Drug)],
        ['query'],
      ),
    'getLabResultsByPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LabResults)],
        ['query'],
      ),
    'getLastDrugVerification' : IDL.Func(
        [],
        [IDL.Opt(DrugVerificationResult)],
        ['query'],
      ),
    'getMedicationsByPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Medication)],
        ['query'],
      ),
    'getPrescriberDetailsByPatientId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PrescriberDetails)],
        ['query'],
      ),
    'getPrescriptionImagesByPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PrescriptionImage)],
        ['query'],
      ),
    'getRestrictedDrugCategories' : IDL.Func(
        [],
        [IDL.Vec(RestrictedDrugCategory)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'refreshAndVerifyDrugTable' : IDL.Func([], [DrugVerificationResult], []),
    'refreshAuthoritativeAggregateDatabase' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePrescriberDetailsForPatient' : IDL.Func(
        [IDL.Text, PrescriberDetails],
        [],
        [],
      ),
    'searchDrugs' : IDL.Func([IDL.Text], [IDL.Vec(Drug)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };