/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdverseDrugReaction {
  'onsetDate' : [] | [Time],
  'adrId' : string,
  'patientId' : string,
  'description' : string,
  'timestamp' : Time,
  'suspectedDrug' : string,
  'severity' : string,
}
export interface BulkDrugStoreUpdateResult {
  'added' : bigint,
  'errors' : Array<string>,
  'duplicates' : bigint,
  'totalAfterStore' : bigint,
  'skippedEmpty' : bigint,
}
export interface CaseNarration {
  'status' : NarrationStatus,
  'content' : string,
  'generatedSummary' : [] | [string],
  'patientId' : string,
  'lastModified' : Time,
  'version' : bigint,
  'narrationId' : string,
  'timestamp' : Time,
}
export interface CategorizedDrugs {
  'all' : Array<DrugWithCategory>,
  'painkillers' : Array<DrugWithCategory>,
  'fdcs' : Array<DrugWithCategory>,
  'others' : Array<DrugWithCategory>,
  'antibiotics' : Array<DrugWithCategory>,
  'vitamins' : Array<DrugWithCategory>,
}
export interface ChatMessage {
  'id' : bigint,
  'sender' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface ClinicallyOrientedInteraction {
  'managementRecommendations' : [] | [string],
  'interactionType' : [] | [InteractionType],
  'references' : Array<string>,
  'evidenceLevel' : [] | [EvidenceLevel],
  'description' : [] | [string],
  'severity' : [] | [Severity],
  'toxicityRisk' : [] | [ToxicityRiskLevel],
  'clinicalEffects' : [] | [string],
  'drugs' : DrugInteractionPair,
}
export interface Drug {
  'status' : DrugStatus,
  'source' : DrugSource,
  'date' : Time,
  'name' : string,
  'description' : string,
  'category' : string,
  'safetyInfo' : string,
}
export type DrugCategoryType = { 'painkillers' : null } |
  { 'other' : null } |
  { 'fdcs' : null } |
  { 'antibiotics' : null } |
  { 'vitamins' : null };
export interface DrugInteraction {
  'interactionType' : InteractionType,
  'references' : Array<string>,
  'evidenceLevel' : EvidenceLevel,
  'description' : string,
  'severity' : Severity,
  'drug1' : string,
  'drug2' : string,
}
export interface DrugInteractionPair { 'drugA' : string, 'drugB' : string }
export interface DrugPairResult {
  'interactionType' : [] | [InteractionType],
  'references' : Array<string>,
  'evidenceLevel' : [] | [EvidenceLevel],
  'description' : [] | [string],
  'severity' : [] | [Severity],
  'drugs' : DrugInteractionPair,
}
export interface DrugSafetyAdvisory {
  'specialPopulations' : SpecialPopulationsGuidance,
  'overallRisk' : [] | [OverallRiskSummary],
  'pairwiseInteractions' : Array<ClinicallyOrientedInteraction>,
}
export type DrugSource = { 'other' : string } |
  { 'cdsco' : null } |
  { 'mimsIndia' : null } |
  { 'applicationData' : null };
export type DrugStatus = { 'banned' : null } |
  { 'approved' : null };
export interface DrugVerificationResult {
  'verifiedBannedDrugs' : Array<Drug>,
  'verificationTimestamp' : Time,
  'allDrugs' : Array<Drug>,
  'verifiedApprovedDrugs' : Array<Drug>,
}
export interface DrugWithCategory {
  'categoryType' : DrugCategoryType,
  'drug' : Drug,
}
export type EvidenceLevel = { 'clinicalTrial' : null } |
  { 'others' : null } |
  { 'regulatoryAgency' : null } |
  { 'metaAnalysis' : null } |
  { 'caseReport' : null } |
  { 'expertOpinion' : null };
export interface ExternalResource {
  'id' : string,
  'url' : string,
  'status' : ResourceStatus,
  'synchronizationLogs' : Array<string>,
  'name' : string,
  'lastUpdated' : Time,
  'description' : string,
  'contentSummary' : [] | [string],
}
export interface FourDrugInteractionInput {
  'drug1' : string,
  'drug2' : string,
  'drug3' : string,
  'drug4' : string,
}
export interface FourDrugInteractionOutput {
  'pairResults' : Array<DrugPairResult>,
  'overallSeverity' : [] | [string],
}
export type InteractionType = { 'pharmacokinetic' : null } |
  { 'both' : null } |
  { 'pharmacodynamic' : null };
export interface LabResults {
  'patientId' : string,
  'labResultsId' : string,
  'timestamp' : Time,
  'bloodPressureDiastolic' : [] | [bigint],
  'creatinine' : [] | [number],
  'bloodPressureSystolic' : [] | [bigint],
  'uricAcid' : [] | [number],
}
export interface Medication {
  'endDate' : [] | [Time],
  'dosage' : [] | [string],
  'patientId' : string,
  'name' : string,
  'medicationId' : string,
  'timestamp' : Time,
  'frequency' : [] | [string],
  'startDate' : [] | [Time],
}
export type NarrationStatus = { 'finalized' : null } |
  { 'reviewed' : null } |
  { 'draft' : null };
export type OCRStatus = { 'pending' : null } |
  { 'processed' : null } |
  { 'failed' : null };
export interface OverallRiskSummary {
  'highestRiskLevel' : [] | [ToxicityRiskLevel],
  'topRecommendation' : [] | [string],
  'overallSeverity' : [] | [Severity],
  'highestSeverityPair' : [] | [DrugInteractionPair],
}
export interface Patient {
  'age' : bigint,
  'bmi' : number,
  'weight' : number,
  'height' : number,
  'patientId' : string,
  'name' : string,
  'nationality' : string,
  'bloodGroup' : [] | [string],
  'address' : [] | [string],
  'gender' : string,
  'timestamp' : Time,
  'phone' : [] | [string],
}
export interface PrescriberDetails {
  'fullName' : string,
  'registrationNumber' : string,
  'email' : string,
  'address' : string,
  'specialization' : string,
  'prefix' : PrescriberPrefix,
  'contactNumber' : string,
}
export type PrescriberPrefix = { 'doctor' : null } |
  { 'pharmacist' : null } |
  { 'practitionerNurse' : null };
export interface PrescriptionImage {
  'id' : string,
  'patientId' : string,
  'errorMessage' : [] | [string],
  'ocrStatus' : OCRStatus,
  'extractedText' : [] | [string],
  'processingTime' : [] | [Time],
  'imageUrl' : string,
  'uploadTime' : Time,
}
export type ResourceStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'redirected' : null } |
  { 'archived' : null } |
  { 'unavailable' : null };
export interface RestrictedDrug {
  'name' : string,
  'description' : string,
  'category' : string,
  'safetyInfo' : string,
}
export interface RestrictedDrugCategory {
  'name' : string,
  'description' : string,
  'drugs' : Array<RestrictedDrug>,
}
export type Severity = { 'major' : null } |
  { 'minor' : null } |
  { 'contraindicated' : null } |
  { 'moderate' : null };
export interface SpecialPopulationsGuidance {
  'lactation' : [] | [string],
  'pediatrics' : [] | [string],
  'pregnancy' : [] | [string],
  'geriatrics' : [] | [string],
}
export type Time = bigint;
export type ToxicityRiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'moderate' : null } |
  { 'unknown' : null };
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addADR' : ActorMethod<
    [string, string, string, string, [] | [Time]],
    { 'status' : string, 'adrId' : [] | [string], 'error' : [] | [string] }
  >,
  'addCaseNarration' : ActorMethod<
    [string, string],
    {
      'status' : string,
      'error' : [] | [string],
      'narrationId' : [] | [string],
    }
  >,
  'addChatMessage' : ActorMethod<[string, string], bigint>,
  'addDrug' : ActorMethod<[Drug], undefined>,
  'addDrugInteraction' : ActorMethod<[DrugInteraction], undefined>,
  'addExternalResource' : ActorMethod<[ExternalResource], undefined>,
  'addLabResults' : ActorMethod<
    [string, [] | [number], [] | [number], [] | [bigint], [] | [bigint]],
    {
      'status' : string,
      'labResultsId' : [] | [string],
      'error' : [] | [string],
    }
  >,
  'addMedication' : ActorMethod<
    [string, string, [] | [string], [] | [string], [] | [Time], [] | [Time]],
    {
      'status' : string,
      'error' : [] | [string],
      'medicationId' : [] | [string],
    }
  >,
  'addNewPatient' : ActorMethod<
    [
      string,
      bigint,
      string,
      number,
      number,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    { 'status' : string, 'patientId' : [] | [string], 'error' : [] | [string] }
  >,
  'addPrescriptionImage' : ActorMethod<
    [string, string],
    { 'status' : string, 'error' : [] | [string], 'imageId' : [] | [string] }
  >,
  'addRestrictedDrugCategory' : ActorMethod<
    [RestrictedDrugCategory],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateDrugDatabaseStore' : ActorMethod<
    [Array<Drug>],
    BulkDrugStoreUpdateResult
  >,
  'bulkUpdateDrugTableStore' : ActorMethod<
    [Array<Drug>],
    BulkDrugStoreUpdateResult
  >,
  'checkDrugInteraction' : ActorMethod<
    [string, string],
    [] | [DrugInteraction]
  >,
  'checkFourDrugInteraction' : ActorMethod<
    [FourDrugInteractionInput],
    FourDrugInteractionOutput
  >,
  'deletePatient' : ActorMethod<
    [string],
    { 'status' : string, 'error' : [] | [string] }
  >,
  'getADRsByPatient' : ActorMethod<[string], Array<AdverseDrugReaction>>,
  'getAllDrugDatabaseStoreDrugs' : ActorMethod<[], Array<Drug>>,
  'getAllDrugTableStoreDrugs' : ActorMethod<[], Array<Drug>>,
  'getAllDrugs' : ActorMethod<[], Array<Drug>>,
  'getAllDrugsFromDatabase' : ActorMethod<[], Array<Drug>>,
  'getAllDrugsFromStore' : ActorMethod<[], Array<Drug>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getApprovedDrugs' : ActorMethod<[], Array<Drug>>,
  'getAuthoritativeDrugDatabase' : ActorMethod<[], Array<Drug>>,
  'getAuthoritativeDrugDatabaseByStatus' : ActorMethod<
    [DrugStatus],
    Array<Drug>
  >,
  'getBannedDrugs' : ActorMethod<[], Array<Drug>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseNarrationsByPatient' : ActorMethod<[string], Array<CaseNarration>>,
  'getCategorizedDrugs' : ActorMethod<[], CategorizedDrugs>,
  'getChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getDrugDatabaseStoreByStatus' : ActorMethod<[DrugStatus], Array<Drug>>,
  'getDrugSafetyAdvisory' : ActorMethod<
    [string, string, string, string],
    DrugSafetyAdvisory
  >,
  'getDrugTableLastRefreshTimestamp' : ActorMethod<[], [] | [Time]>,
  'getDrugTableStoreByStatus' : ActorMethod<[DrugStatus], Array<Drug>>,
  'getDrugTableVerificationReport' : ActorMethod<
    [],
    {
      'lastVerificationTimestamp' : [] | [Time],
      'bannedDrugs' : bigint,
      'lastVerifiedDrugCount' : [] | [bigint],
      'approvedDrugs' : bigint,
      'totalDrugs' : bigint,
    }
  >,
  'getExternalResources' : ActorMethod<[], Array<ExternalResource>>,
  'getFilteredDrugs' : ActorMethod<[[] | [DrugStatus]], Array<Drug>>,
  'getLabResultsByPatient' : ActorMethod<[string], Array<LabResults>>,
  'getLastDrugVerification' : ActorMethod<[], [] | [DrugVerificationResult]>,
  'getMedicationsByPatient' : ActorMethod<[string], Array<Medication>>,
  'getPrescriberDetailsByPatientId' : ActorMethod<
    [string],
    [] | [PrescriberDetails]
  >,
  'getPrescriptionImagesByPatient' : ActorMethod<
    [string],
    Array<PrescriptionImage>
  >,
  'getRestrictedDrugCategories' : ActorMethod<
    [],
    Array<RestrictedDrugCategory>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'refreshAndVerifyDrugTable' : ActorMethod<[], DrugVerificationResult>,
  'refreshAuthoritativeAggregateDatabase' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePrescriberDetailsForPatient' : ActorMethod<
    [string, PrescriberDetails],
    undefined
  >,
  'searchDrugs' : ActorMethod<[string], Array<Drug>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];